---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: directory
  path: Joey_Site/content
  label: Pages
  create: all
  match: "*"
- type: directory
  path: Joey_Site/content/chinese
  label: Chinese
  create: all
  match: "**/*"
- type: directory
  path: Joey_Site/content/english
  label: English
  create: all
  match: "**/*"
- type: directory
  path: Joey_Site/data
  label: DATA
  create: all
  match: "*"
- type: directory
  path: Joey_Site/data/en
  label: DATA-en
  create: all
  match: "*"
- type: directory
  path: Joey_Site/data/ch
  label: DATA-ch
  create: all
  match: "*"
upload_dir: Joey_Site/static/images
public_path: "/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.63.2
  preview_output_directory: public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: hugo server -D -E -F --port 8080 --bind 0.0.0.0 --renderToDisk
    -d public
version: 0.63.2
