---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: document
  path: Joey_Site/config.toml
  label: Config
  match: "**/*"
- type: heading
  label: Banner
- type: document
  path: Joey_Site/data/ch/banner.yml
  label: banner-ch
- type: document
  path: Joey_Site/data/en/banner.yml
  label: banner-en
- type: heading
  label: Biography
- type: document
  path: Joey_Site/data/ch/biography.yml
  label: bio-ch
- type: document
  path: Joey_Site/data/en/biography.yml
  label: bio-en
- type: heading
  label: Perf. Intro
- type: directory
  path: Joey_Site/content/chinese/introduction
  label: Performance-ch
  create: all
  match: "*"
- type: directory
  path: Joey_Site/content/english/introduction
  label: Performance-en
  create: all
  match: "*"
- type: heading
  label: Experience
- type: document
  path: Joey_Site/data/ch/experience.yml
  label: experience-ch
- type: document
  path: Joey_Site/data/en/experience.yml
  label: experience-en
- type: heading
  label: Featured Photos
- type: document
  path: Joey_Site/data/ch/portfolio.yml
  label: portfolio-ch
- type: document
  path: Joey_Site/data/en/portfolio.yml
  label: portfolio-en
- type: heading
  label: Blog
- type: directory
  path: Joey_Site/content/english/blog
  label: blog-en
  create: all
  match: "*"
- type: directory
  path: Joey_Site/content/chinese/blog
  label: blog-ch
  create: all
  match: "*"
- type: heading
  label: Perf. Info
- type: document
  path: Joey_Site/data/ch/showtime.yml
  label: showtime-ch
- type: document
  path: Joey_Site/data/en/showtime.yml
  label: showtime-en
- type: heading
  label: Contact
- type: document
  path: Joey_Site/data/ch/contact.yml
  label: contact-ch
- type: document
  path: Joey_Site/data/en/contact.yml
  label: contact-en
- type: heading
  label: Author
- type: directory
  path: Joey_Site/content/chinese/author
  label: author-ch
  create: all
  match: "*"
- type: directory
  path: Joey_Site/content/english/author
  label: author-en
  create: all
  match: "*"
- type: heading
  label: Other
- type: document
  path: Joey_Site/i18n/ch.yaml
  label: Abbv. Name-ch
- type: document
  path: Joey_Site/i18n/en.yaml
  label: Abbr. Name-en
upload_dir: Joey_Site/static/images
public_path: "/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.63.2
  preview_output_directory: public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: hugo server -D -E -F --port 8080 --bind 0.0.0.0 --renderToDisk
    -d public
version: 0.63.2
