---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: heading
  label: Banner
- type: document
  path: Joey_Site/data/en/banner.yml
  label: banner-en
  read_only: false
- type: document
  path: Joey_Site/data/ch/banner.yml
  label: banner-ch
  match: "**/*"
- type: heading
  label: Biography
- type: heading
  label: Performance Introduction
- type: heading
  label: Experience
- type: heading
  label: Featured Photos
- type: heading
  label: Blog
- type: directory
  path: Joey_Site/content/english/blog
  label: blog-en
  create: all
  match: "*"
- type: directory
  path: Joey_Site/content/chinese/blog
  label: blog-ch
  create: all
  match: "*"
- type: heading
  label: Contact
- type: directory
  path: Joey_Site/content/chinese
  label: Chinese
  create: all
  match: "**/*"
- type: directory
  path: Joey_Site/content/english
  label: English
  create: all
  match: "**/*"
- type: directory
  path: Joey_Site/data/en
  label: DATA-en
  create: all
  match: "*"
- type: directory
  path: Joey_Site/data/ch
  label: DATA-ch
  create: all
  match: "*"
upload_dir: Joey_Site/static/images
public_path: "/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.63.2
  preview_output_directory: public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: hugo server -D -E -F --port 8080 --bind 0.0.0.0 --renderToDisk
    -d public
version: 0.63.2
